#!/usr/bin/env php
<?php

use Core\Boot;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$status = Boot::app()->handleCommand(new ArgvInput);

exit($status);
