name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Provide code examples if applicable
      render: php
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package does this feature relate to?
      options:
        - Core
        - Admin
        - API
        - MCP
        - Multiple packages
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered backwards compatibility
          required: true
        - label: This feature aligns with the project's goals
          required: false
